apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-fe-angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-fe-angular
  template:
    metadata:
      labels:
        app: customer-fe-angular
    spec:
      containers:
        - name: customer-fe-angular
          image: docker.io/hai2k2tt/customer-fe-angular:2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: nginx-config
          configMap:
            name: customer-fe-angular-nginx
