enabled: true
namespace: microservices
image: docker.io/hai2k2tt/customer-wallet-fe:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3006
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
config:
  apiBaseUrl: http://api-gateway.microservices.svc.cluster.local:9000/api
  nextPublicApiBaseUrl: http://api.haint.fyi/api
  authUrl: http://customer-wallet-fe.haint.fyi
  authIssuer: http://keycloak.haint.fyi/realms/ecommerce-customer
  authIssuerInternal: http://keycloak.microservices.svc.cluster.local:8080/realms/ecommerce-customer
  authClientId: customer-fe-client
  authClientSecret: ""
  authScope: openid profile offline_access
  authCookiePrefix: customer-wallet-fe
  authCookieDomain: ""
  authBasePath: /api/customer-wallet-fe/auth
  authSecret: replace-with-a-long-random-string
