apiVersion: v2
name: applications
description: Application workloads for the microservices demo
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: api-gateway
    alias: apiGateway
    version: 0.1.0
    repository: "file://charts/api-gateway"
    condition: apiGateway.enabled
  - name: product-service
    alias: productService
    version: 0.1.0
    repository: "file://charts/product-service"
    condition: productService.enabled
  - name: order-service
    alias: orderService
    version: 0.1.0
    repository: "file://charts/order-service"
    condition: orderService.enabled
  - name: inventory-service
    alias: inventoryService
    version: 0.1.0
    repository: "file://charts/inventory-service"
    condition: inventoryService.enabled
  - name: notification-service
    alias: notificationService
    version: 0.1.0
    repository: "file://charts/notification-service"
    condition: notificationService.enabled
  - name: payment-service
    alias: paymentService
    version: 0.1.0
    repository: "file://charts/payment-service"
    condition: paymentService.enabled
  - name: wallet-service
    alias: walletService
    version: 0.1.0
    repository: "file://charts/wallet-service"
    condition: walletService.enabled
  - name: shop-service
    alias: shopService
    version: 0.1.0
    repository: "file://charts/shop-service"
    condition: shopService.enabled
  - name: customer-service
    alias: customerService
    version: 0.1.0
    repository: "file://charts/customer-service"
    condition: customerService.enabled
  - name: landing-fe
    alias: landingFe
    version: 0.1.0
    repository: "file://charts/landing-fe"
    condition: landingFe.enabled
  - name: admin-fe
    alias: adminFe
    version: 0.1.0
    repository: "file://charts/admin-fe"
    condition: adminFe.enabled
  - name: shop-fe
    alias: shopFe
    version: 0.1.0
    repository: "file://charts/shop-fe"
    condition: shopFe.enabled
  - name: customer-fe-next
    alias: customerFeNext
    version: 0.1.0
    repository: "file://charts/customer-fe-next"
    condition: customerFeNext.enabled
  - name: customer-wallet-fe
    alias: customerWalletFe
    version: 0.1.0
    repository: "file://charts/customer-wallet-fe"
    condition: customerWalletFe.enabled
  - name: shop-wallet-fe
    alias: shopWalletFe
    version: 0.1.0
    repository: "file://charts/shop-wallet-fe"
    condition: shopWalletFe.enabled
