apiVersion: v2
name: infrastructure
description: Infrastructure stack for the microservices demo
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mysql
    version: 0.1.0
    repository: "file://charts/mysql"
  - name: mongodb
    version: 0.1.0
    repository: "file://charts/mongodb"
  - name: kafka
    version: 0.1.0
    repository: "file://charts/kafka"
  - name: keycloak
    version: 0.1.0
    repository: "file://charts/keycloak"
  - name: mailhog
    version: 0.1.0
    repository: "file://charts/mailhog"
  - name: observability
    version: 0.1.0
    repository: "file://charts/observability"

