apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: {{ .Values.namespace }}
data:
  kc_db: 'mysql'
  kc_db_url_host: 'keycloak-mysql'
  kc_db_url_database: 'keycloak'
  kc_db_username: 'keycloak'
  keycloak_admin: 'admin'
  kc_http_enabled: {{ .Values.kcHttpEnabled | default "true" | quote }}
  kc_hostname: {{ .Values.hostname | quote }}
  kc_proxy_headers: 'xforwarded'
  kc_hostname_strict: {{ .Values.kcHostnameStrict | default "false" | quote }}
  kc_hostname_strict_https: {{ .Values.kcHostnameStrictHttps | default "false" | quote }}
  ecommerce-admin-realm.json: |-
    {
      "realm": "ecommerce-admin",
      "enabled": true,
      "sslRequired": "none",
      "registrationAllowed": false,
      "loginWithEmailAllowed": true,
      "roles": {
        "realm": [
          {
            "name": "admin",
            "description": "Administration frontend users",
            "composite": false,
            "clientRole": false,
            "attributes": {}
          }
        ]
      },
      "clients": [
        {
          "clientId": "admin-fe-client",
          "name": "Admin Frontend",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [
            "http://localhost:3002",
            "http://localhost:3002/api/auth/callback/keycloak",
            "http://localhost:3002/api/admin-fe/auth/callback/keycloak",
            "http://admin-fe.local:8080",
            "http://admin-fe.local:8080/*",
            "http://admin-fe.local:8080/api/auth/callback/keycloak",
            "http://admin-fe.local:8080/api/admin-fe/auth/callback/keycloak",
            "http://admin-fe.haint.fyi",
            "http://admin-fe.haint.fyi/*",
            "http://admin-fe.haint.fyi/api/auth/callback/keycloak",
            "http://admin-fe.haint.fyi/api/admin-fe/auth/callback/keycloak"
          ],
          "webOrigins": [
            "*"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "protocolMappers": [
            {
              "name": "user id",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "id",
                "claim.name": "user_id",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ],
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "roles",
            "profile",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        }
      ]
    }
  ecommerce-customer-realm.json: |-
    {
      "realm": "ecommerce-customer",
      "enabled": true,
      "sslRequired": "none",
      "registrationAllowed": true,
      "loginWithEmailAllowed": true,
      "roles": {
        "realm": [
          {
            "name": "customer",
            "description": "Customer frontend users",
            "composite": false,
            "clientRole": false,
            "attributes": {}
          }
        ]
      },
      "clients": [
        {
          "clientId": "customer-fe-client",
          "name": "Customer Frontend",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [
            "http://localhost:4200",
            "http://localhost:3004",
            "http://localhost:3004/api/auth/callback/keycloak",
            "http://localhost:3004/api/customer-fe-next/auth/callback/keycloak",
            "http://customer-fe-next.local:8080",
            "http://customer-fe-next.local:8080/*",
            "http://customer-fe-next.local:8080/api/auth/callback/keycloak",
            "http://customer-fe-next.local:8080/api/customer-fe-next/auth/callback/keycloak",
            "http://customer-fe-next.haint.fyi",
            "http://customer-fe-next.haint.fyi/*",
            "http://customer-fe-next.haint.fyi/api/auth/callback/keycloak",
            "http://customer-fe-next.haint.fyi/api/customer-fe-next/auth/callback/keycloak",
            "http://customer-fe-angular.local:8080",
            "http://customer-fe-angular.local:8080/*",
            "http://customer-fe-angular.haint.fyi",
            "http://customer-fe-angular.haint.fyi/*"
          ],
          "webOrigins": [
            "*"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "protocolMappers": [
            {
              "name": "user id",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "id",
                "claim.name": "user_id",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ],
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "roles",
            "profile",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        }
      ]
    }
  ecommerce-shop-realm.json: |-
    {
      "realm": "ecommerce-shop",
      "enabled": true,
      "sslRequired": "none",
      "registrationAllowed": true,
      "loginWithEmailAllowed": true,
      "roles": {
        "realm": [
          {
            "name": "shop",
            "description": "Shop frontend users",
            "composite": false,
            "clientRole": false,
            "attributes": {}
          }
        ]
      },
      "clients": [
        {
          "clientId": "shop-fe-client",
          "name": "Shop Frontend",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [
            "http://localhost:3003",
            "http://localhost:3003/api/auth/callback/keycloak",
            "http://localhost:3003/api/shop-fe/auth/callback/keycloak",
            "http://shop-fe.local:8080",
            "http://shop-fe.local:8080/*",
            "http://shop-fe.local:8080/api/auth/callback/keycloak",
            "http://shop-fe.local:8080/api/shop-fe/auth/callback/keycloak",
            "http://shop-fe.haint.fyi",
            "http://shop-fe.haint.fyi/*",
            "http://shop-fe.haint.fyi/api/auth/callback/keycloak",
            "http://shop-fe.haint.fyi/api/shop-fe/auth/callback/keycloak"
          ],
          "webOrigins": [
            "*"
          ],
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "publicClient": true,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "oidc.ciba.grant.enabled": "false",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "backchannel.logout.revoke.offline.tokens": "false"
          },
          "protocolMappers": [
            {
              "name": "user id",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-property-mapper",
              "consentRequired": false,
              "config": {
                "user.attribute": "id",
                "claim.name": "user_id",
                "jsonType.label": "String",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "userinfo.token.claim": "true"
              }
            }
          ],
          "fullScopeAllowed": true,
          "defaultClientScopes": [
            "web-origins",
            "acr",
            "roles",
            "profile",
            "email"
          ],
          "optionalClientScopes": [
            "address",
            "phone",
            "offline_access",
            "microprofile-jwt"
          ]
        }
      ]
    }
