apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          ports:
            - containerPort: 8080
          args: ["start-dev", "--import-realm"]
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db_url_host
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db_url_database
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_db_username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: db_password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: keycloak_admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: keycloak_admin_password
            - name: KC_HTTP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_http_enabled
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_hostname
            - name: KC_PROXY_HEADERS
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_proxy_headers
            - name: KC_HOSTNAME_STRICT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_hostname_strict
            - name: KC_HOSTNAME_STRICT_HTTPS
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc_hostname_strict_https
          volumeMounts:
            - name: keycloak-config
              mountPath: /opt/keycloak/data/import/
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
