apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db_password: {{ .Values.dbPassword | b64enc }}
  keycloak_admin_password: {{ .Values.adminPassword | b64enc }}
