spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8084
        specific:
          avro:
            reader: true

server:
  port: 8083

app:
  notifications:
    shop-topic: shop-notifications

shop:
  service:
    url: http://localhost:8086

management:
  health:
    mongo:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0

loki:
  url: http://localhost:3100/loki/api/v1/push
