apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://schema-registry.microservices.svc.cluster.local:8081"
