apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: mailhog
          image: {{ .Values.image }}
          ports:
            - containerPort: 1025
            - containerPort: 8025
          resources:
{{ toYaml .Values.resources | nindent 12 }}
