apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin-fe-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - admin-fe.local
  rules:
    - backendRefs:
        - name: admin-fe
          port: 3002
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shop-fe-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - shop-fe.local
  rules:
    - backendRefs:
        - name: shop-fe
          port: 3003
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: customer-fe-next-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - customer-fe-next.local
  rules:
    - backendRefs:
        - name: customer-fe-next
          port: 3004
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: customer-fe-angular-api-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - customer-fe-angular.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api
      backendRefs:
        - name: api-gateway
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: customer-fe-angular-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - customer-fe-angular.local
  rules:
    - backendRefs:
        - name: customer-fe-angular
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - api.local
  rules:
    - backendRefs:
        - name: api-gateway
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - keycloak.local
  rules:
    - backendRefs:
        - name: keycloak
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kafka-ui-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - kafka-ui.local
  rules:
    - backendRefs:
        - name: kafka-ui
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - grafana.local
  rules:
    - backendRefs:
        - name: grafana
          port: 3000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tempo-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - tempo.local
  rules:
    - backendRefs:
        - name: tempo
          port: 3100
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - prometheus.local
  rules:
    - backendRefs:
        - name: prometheus
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mailhog-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - mailhog.local
  rules:
    - backendRefs:
        - name: mailhog
          port: 8025
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: schema-registry-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - schema-registry.local
  rules:
    - backendRefs:
        - name: schema-registry
          port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-route
spec:
  parentRefs:
    - name: api-gateway
  hostnames:
    - loki.local
  rules:
    - backendRefs:
        - name: loki
          port: 3100
