apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
data:
  schema_registry_host_name: 'schema-registry'
  schema_registry_kafkastore_bootstrap_servers: 'broker:29092'
  schema_registry_listeners: 'http://schema-registry:8081'