apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: loki
          image: grafana/loki:main
          ports:
            - containerPort: 3100
          args: ["-config.file=/etc/loki/local-config.yaml"]
          resources:
{{ toYaml .Values.resources | nindent 12 }}
