nginxGateway:
  watchNamespaces:
    - microservices

nginx:
  kind: daemonSet
  pod:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
  container:
    hostPorts:
      - port: 80
        containerPort: 80
      - port: 443
        containerPort: 443
  service:
    type: ClusterIP
