apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-next
  template:
    metadata:
      labels:
        app: frontend-next
    spec:
      containers:
        - name: frontend-next
          image: hai2k2tt/frontend-next:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://api.local:8080/api"
            - name: AUTH_URL
              value: "http://frontend-next.local:8080"
            - name: NEXTAUTH_URL
              value: "http://frontend-next.local:8080"
            - name: AUTH_ISSUER
              value: "http://keycloak.local:8080/realms/spring-microservices-security-realm"
            - name: AUTH_ISSUER_INTERNAL
              value: "http://keycloak.microservices.svc.cluster.local:8080/realms/spring-microservices-security-realm"
            - name: AUTH_CLIENT_ID
              value: "angular-client"
            - name: AUTH_CLIENT_SECRET
              value: ""
            - name: AUTH_SCOPE
              value: "openid profile offline_access"
            - name: AUTH_SECRET
              value: "replace-with-a-long-random-string"
          ports:
            - containerPort: 3001
