{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: {{ .Values.namespace }}
  labels:
    app: wallet-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      labels:
        app: wallet-service
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: wallet-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: wallet-service-config
                  key: SPRING_DATASOURCE_URL
            - name: CUSTOMER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CUSTOMER_SERVICE_URL
            - name: SHOP_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SHOP_SERVICE_URL
            - name: APP_PERMISSIONS_FILE
              valueFrom:
                configMapKeyRef:
                  name: wallet-service-config
                  key: APP_PERMISSIONS_FILE
          resources:
{{ toYaml .Values.resources | nindent 12 }}
{{- end }}
