apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-config
data:
  kafka_broker_id: '1'
  kafka_zookeeper_connect: 'zookeeper:2181'
  kafka_listener_security_protocol_map: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  kafka_advertised_listeners: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092'
  kafka_offsets_topic_replication_factor: '1'