apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: mongo
          image: mongo:7.0.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongo_initdb_root_username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets
                  key: mongo_initdb_root_password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: mongo_initdb_database
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
