apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  strategy: { }
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - image: grafana/loki:main
          name: loki
          resources: { }
          ports:
            - containerPort: 3100
          args: ["-config.file=/etc/loki/local-config.yaml"]
