apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: docker.io/hai2k2tt/product-service:2-arm64
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: SPRING_DATASOURCE_URL
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: MINIO_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root_user
            - name: MINIO_PUBLIC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: MINIO_PUBLIC_ENDPOINT
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: root_password
            - name: MINIO_BUCKET_PRODUCT_IMAGES
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: MINIO_BUCKET_PRODUCT_IMAGES
            - name: MINIO_PRODUCT_IMAGES_PUBLIC_PATH
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: MINIO_PRODUCT_IMAGES_PUBLIC_PATH
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
