apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: docker.io/hai2k2tt/payment-service:2-arm64
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: SPRING_DATASOURCE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: WALLET_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: WALLET_SERVICE_URL
            - name: APP_PERMISSIONS_FILE
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: APP_PERMISSIONS_FILE
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
