apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-mysql
  name: keycloak-mysql-headless
spec:
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: keycloak-mysql
