apiVersion: v1
kind: Service
metadata:
  labels:
    app: tempo
  name: tempo
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      targetPort: 3100
      name: tempo
    - port: 9411
      protocol: TCP
      targetPort: 9411
      name: zipkin
  selector:
    app: tempo
