apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tempo
  name: tempo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  strategy: { }
  template:
    metadata:
      labels:
        app: tempo
    spec:
      enableServiceLinks: false
      containers:
        - image: grafana/tempo:2.2.2
          name: tempo
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 3100
            - containerPort: 9411
          args: [ "-config.file=/etc/tempo.yaml" ]
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
              readOnly: true
            - name: tempo-tmp
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-tmp
          persistentVolumeClaim:
            claimName: tempo-pvc
