apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      enableServiceLinks: false
      containers:
        - name: grafana
          image: grafana/grafana:10.1.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: gf_auth_anonymous_enabled
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: gf_auth_anonymous_org_role
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: gf_auth_disable_login_form
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: true
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-config
