{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: {{ .Values.namespace }}
  labels:
    app: customer-service
spec:
  type: ClusterIP
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
