enabled: true
namespace: microservices
image: docker.io/hai2k2tt/customer-fe-next:2
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3004
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
config:
  apiBaseUrl: http://api-gateway.microservices.svc.cluster.local:9000/api
  nextPublicApiBaseUrl: http://api.haint.fyi/api
  authUrl: http://customer-fe-next.haint.fyi
  authIssuer: http://keycloak.haint.fyi/realms/spring-microservices-security-realm
  authIssuerInternal: http://keycloak.microservices.svc.cluster.local:8080/realms/spring-microservices-security-realm
  authClientId: angular-client
  authClientSecret: ""
  authScope: openid profile offline_access
  authSecret: replace-with-a-long-random-string
