apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      enableServiceLinks: false
      containers:
        - name: tempo
          image: grafana/tempo:2.2.2
          ports:
            - containerPort: 3100
            - containerPort: 9411
          args: ["-config.file=/etc/tempo.yaml"]
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
              readOnly: true
            - name: tempo-tmp
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
        - name: tempo-tmp
          persistentVolumeClaim:
            claimName: tempo-pvc
