apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: {{ .Values.namespace }}
  labels:
    app: tempo
spec:
  type: ClusterIP
  ports:
    - name: tempo
      port: 3100
      targetPort: 3100
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
  selector:
    app: tempo
