apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    scrape_configs:
      - job_name: 'api-gateway'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'api-gateway.microservices.svc.cluster.local:9000' ]
      - job_name: 'product-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'product-service.microservices.svc.cluster.local:8080' ]
            labels:
              application: 'Product Service'
      - job_name: 'order-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'order-service.microservices.svc.cluster.local:8081' ]
            labels:
              application: 'Order Service'
      - job_name: 'inventory-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'inventory-service.microservices.svc.cluster.local:8082' ]
            labels:
              application: 'Inventory Service'
      - job_name: 'notification-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'notification-service.microservices.svc.cluster.local:8083' ]
            labels:
              application: 'Notification Service'
      - job_name: 'payment-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'payment-service.microservices.svc.cluster.local:8085' ]
            labels:
              application: 'Payment Service'
      - job_name: 'shop-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'shop-service.microservices.svc.cluster.local:8086' ]
            labels:
              application: 'Shop Service'
      - job_name: 'customer-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'customer-service.microservices.svc.cluster.local:8087' ]
            labels:
              application: 'Customer Service'
