enabled: true
namespace: microservices
image: hai2k2tt/order-service:1.0-SNAPSHOT
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8081
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
config:
  datasourceUrl: jdbc:mysql://mysql.microservices.svc.cluster.local:3306/order_service
  schemaRegistryUrl: http://schema-registry.microservices.svc.cluster.local:8081
