apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://keycloak.microservices.svc.cluster.local:8080/realms/spring-microservices-security-realm"
