apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  APP_SECURITY_CUSTOMER_ISSUER_URI: "http://keycloak.microservices.svc.cluster.local:8080/realms/ecommerce-customer"
  APP_SECURITY_SHOP_ISSUER_URI: "http://keycloak.microservices.svc.cluster.local:8080/realms/ecommerce-shop"
  APP_SECURITY_ADMIN_ISSUER_URI: "http://keycloak.microservices.svc.cluster.local:8080/realms/ecommerce-admin"
