apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docker.io/hai2k2tt/api-gateway:2-amd64
          ports:
            - containerPort: 9000
          env:
            - name: APP_SECURITY_CUSTOMER_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_CUSTOMER_ISSUER_URI
            - name: APP_SECURITY_CUSTOMER_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_CUSTOMER_JWK_SET_URI
            - name: APP_SECURITY_SHOP_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_SHOP_ISSUER_URI
            - name: APP_SECURITY_SHOP_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_SHOP_JWK_SET_URI
            - name: APP_SECURITY_ADMIN_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_ADMIN_ISSUER_URI
            - name: APP_SECURITY_ADMIN_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: api-gateway-config
                  key: APP_SECURITY_ADMIN_JWK_SET_URI
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: INVENTORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: INVENTORY_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PAYMENT_SERVICE_URL
            - name: SHOP_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SHOP_SERVICE_URL
            - name: CUSTOMER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CUSTOMER_SERVICE_URL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
