{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: {{ .Values.namespace }}
data:
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: {{ .Values.config.schemaRegistryUrl | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
