apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-config
  namespace: {{ .Values.namespace }}
data:
  schema_registry_host_name: 'schema-registry'
  schema_registry_kafkastore_bootstrap_servers: 'PLAINTEXT://broker:29092'
  schema_registry_listeners: 'http://0.0.0.0:8081'
