apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      enableServiceLinks: false
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                configMapKeyRef:
                  name: schema-registry-config
                  key: schema_registry_host_name
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: schema-registry-config
                  key: schema_registry_kafkastore_bootstrap_servers
            - name: SCHEMA_REGISTRY_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: schema-registry-config
                  key: schema_registry_listeners
          resources:
{{ toYaml .Values.resources | nindent 12 }}
