apiVersion: v2
name: keycloak
description: Keycloak server
version: 0.1.0
appVersion: "24.0.1"
dependencies:
  - name: keycloak-mysql
    version: 0.1.0
    repository: "file://charts/keycloak-mysql"

