namespace: microservices

dbPassword: password
adminPassword: admin
hostname: keycloak.haint.fyi
redirectUris:
  - http://frontend.haint.fyi
  - http://frontend.haint.fyi/*
  - http://frontend-next.haint.fyi
  - http://frontend-next.haint.fyi/*
  - http://frontend-next.haint.fyi/api/auth/callback/keycloak
kcHttpEnabled: "true"
kcHostnameStrict: "false"
kcHostnameStrictHttps: "false"
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
keycloak-mysql:
  rootPassword: root
  password: password
