namespace: microservices

dbPassword: password
adminPassword: admin
hostname: keycloak.haint.fyi
redirectUris:
  - http://admin-fe.haint.fyi
  - http://admin-fe.haint.fyi/*
  - http://admin-fe.haint.fyi/api/auth/callback/keycloak
  - http://admin-fe.haint.fyi/api/admin-fe/auth/callback/keycloak
  - http://shop-fe.haint.fyi
  - http://shop-fe.haint.fyi/*
  - http://shop-fe.haint.fyi/api/auth/callback/keycloak
  - http://shop-fe.haint.fyi/api/shop-fe/auth/callback/keycloak
  - http://customer-fe-next.haint.fyi
  - http://customer-fe-next.haint.fyi/*
  - http://customer-fe-next.haint.fyi/api/auth/callback/keycloak
  - http://customer-fe-next.haint.fyi/api/customer-fe-next/auth/callback/keycloak
  - http://customer-wallet-fe.haint.fyi
  - http://customer-wallet-fe.haint.fyi/*
  - http://customer-wallet-fe.haint.fyi/api/customer-wallet-fe/auth/callback/keycloak
  - http://shop-wallet-fe.haint.fyi
  - http://shop-wallet-fe.haint.fyi/*
  - http://shop-wallet-fe.haint.fyi/api/shop-wallet-fe/auth/callback/keycloak
  - http://customer-fe-angular.haint.fyi
  - http://customer-fe-angular.haint.fyi/*
kcHttpEnabled: "true"
kcHostnameStrict: "false"
kcHostnameStrictHttps: "false"
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
keycloak-mysql:
  rootPassword: root
  password: password
