enabled: true
namespace: microservices
image: docker.io/hai2k2tt/api-gateway:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 9000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
config:
  issuerUri: http://keycloak.haint.fyi/realms/spring-microservices-security-realm
