{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-fe
  namespace: {{ .Values.namespace }}
  labels:
    app: landing-fe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: landing-fe
  template:
    metadata:
      labels:
        app: landing-fe
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: landing-fe
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: NEXT_PUBLIC_ADMIN_FE_URL
              value: {{ required "landing-fe config.adminFeUrl is required" .Values.config.adminFeUrl | quote }}
            - name: NEXT_PUBLIC_SHOP_FE_URL
              value: {{ required "landing-fe config.shopFeUrl is required" .Values.config.shopFeUrl | quote }}
            - name: NEXT_PUBLIC_CUSTOMER_FE_URL
              value: {{ required "landing-fe config.customerFeUrl is required" .Values.config.customerFeUrl | quote }}
            - name: NEXT_PUBLIC_CUSTOMER_WALLET_FE_URL
              value: {{ required "landing-fe config.customerWalletFeUrl is required" .Values.config.customerWalletFeUrl | quote }}
            - name: NEXT_PUBLIC_SHOP_WALLET_FE_URL
              value: {{ required "landing-fe config.shopWalletFeUrl is required" .Values.config.shopWalletFeUrl | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
{{- end }}
