apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  init.sql: |
    CREATE DATABASE product_service;
    CREATE DATABASE payment_service;
    CREATE DATABASE shop_service;
    CREATE DATABASE customer_service;
