{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: payment-service
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: SPRING_DATASOURCE_URL
            - name: LOKI_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOKI_URL
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
          resources:
{{ toYaml .Values.resources | nindent 12 }}
{{- end }}
