apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-mysql-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: 'standard'
  volumeName: keycloak-mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
