apiVersion: v1
kind: Secret
metadata:
  name: keycloak-mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql_root_password: {{ .Values.rootPassword | b64enc }}
  mysql_password: {{ .Values.password | b64enc }}
