apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-mysql
spec:
  serviceName: keycloak-mysql-headless
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-mysql
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak-mysql
    spec:
      containers:
        - name: keycloak-mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-mysql-secrets
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-mysql-config
                  key: mysql_database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: keycloak-mysql-config
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-mysql-secrets
                  key: mysql_password
          volumeMounts:
            - name: keycloak-mysql-data
              mountPath: /var/lib/mysql
          resources:
{{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: keycloak-mysql-data
          persistentVolumeClaim:
            claimName: keycloak-mysql-pvc
