namespace: microservices

gateway:
  name: api-gateway
  className: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
routes:
  - name: frontend-route
    hostname: frontend.haint.fyi
    backendRefName: frontend
    backendRefPort: 80
  - name: frontend-next-route
    hostname: frontend-next.haint.fyi
    backendRefName: frontend-next
    backendRefPort: 3001
  - name: api-route
    hostname: api.haint.fyi
    backendRefName: api-gateway
    backendRefPort: 9000
  - name: keycloak-route
    hostname: keycloak.haint.fyi
    backendRefName: keycloak
    backendRefPort: 8080
  - name: kafka-ui-route
    hostname: kafka-ui.haint.fyi
    backendRefName: kafka-ui
    backendRefPort: 8080
  - name: grafana-route
    hostname: grafana.haint.fyi
    backendRefName: grafana
    backendRefPort: 3000
  - name: tempo-route
    hostname: tempo.haint.fyi
    backendRefName: tempo
    backendRefPort: 3100
  - name: prometheus-route
    hostname: prometheus.haint.fyi
    backendRefName: prometheus
    backendRefPort: 9090
  - name: mailhog-route
    hostname: mailhog.haint.fyi
    backendRefName: mailhog
    backendRefPort: 8025
  - name: schema-registry-route
    hostname: schema-registry.haint.fyi
    backendRefName: schema-registry
    backendRefPort: 8081
  - name: loki-route
    hostname: loki.haint.fyi
    backendRefName: loki
    backendRefPort: 3100
