namespace: microservices

gateway:
  name: api-gateway
  className: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: haint-fyi-tls
      allowedRoutes:
        namespaces:
          from: Same

certManager:
  enabled: true
  clusterIssuer:
    create: true
    name: letsencrypt-prod
    email: admin@haint.fyi
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRefName: letsencrypt-prod-account-key
  certificate:
    create: true
    name: haint-fyi-tls
    secretName: haint-fyi-tls
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
    dnsNames: []
routes:
  - name: api-route
    hostname: api.haint.fyi
    backendRefName: api-gateway
    backendRefPort: 9000
  - name: keycloak-route
    hostname: keycloak.haint.fyi
    backendRefName: keycloak
    backendRefPort: 8080
  - name: kafka-ui-route
    hostname: kafka-ui.haint.fyi
    backendRefName: kafka-ui
    backendRefPort: 8080
  - name: minio-route
    hostname: minio.haint.fyi
    backendRefName: minio
    backendRefPort: 9000
  - name: schema-registry-route
    hostname: schema-registry.haint.fyi
    backendRefName: schema-registry
    backendRefPort: 8081
  - name: landing-fe-route
    hostname: landing-fe.haint.fyi
    backendRefName: landing-fe
    backendRefPort: 3005
  - name: admin-fe-route
    hostname: admin-fe.haint.fyi
    backendRefName: admin-fe
    backendRefPort: 3002
  - name: shop-fe-route
    hostname: shop-fe.haint.fyi
    backendRefName: shop-fe
    backendRefPort: 3003
  - name: customer-fe-next-route
    hostname: customer-fe-next.haint.fyi
    backendRefName: customer-fe-next
    backendRefPort: 3004
  - name: customer-wallet-fe-route
    hostname: customer-wallet-fe.haint.fyi
    backendRefName: customer-wallet-fe
    backendRefPort: 3006
  - name: shop-wallet-fe-route
    hostname: shop-wallet-fe.haint.fyi
    backendRefName: shop-wallet-fe
    backendRefPort: 3007

proxySettingsPolicies:
  - name: frontend-proxy-settings
    targetRefs:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: landing-fe-route
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: admin-fe-route
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: shop-fe-route
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: customer-fe-next-route
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: customer-wallet-fe-route
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
        name: shop-wallet-fe-route
    buffering:
      bufferSize: 32k
      buffers:
        number: 8
        size: 32k
      busyBuffersSize: 64k
