enabled: true
namespace: microservices
image: docker.io/hai2k2tt/product-service:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
config:
  datasourceUrl: jdbc:postgresql://postgres.microservices.svc.cluster.local:5432/product_service
  minioEndpoint: http://minio.microservices.svc.cluster.local:9000
  minioPublicEndpoint: http://minio.haint.fyi
  minioSecretName: minio-secrets
  minioProductImagesBucket: product-images
  minioProductImagesPublicPath: /api/product/images
