{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: customer-fe-angular
  namespace: {{ .Values.namespace }}
  labels:
    app: customer-fe-angular
spec:
  type: ClusterIP
  selector:
    app: customer-fe-angular
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
{{- end }}
