apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy: { }
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:7.5.0
          name: zookeeper
          resources: { }
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              valueFrom:
                configMapKeyRef:
                  key: zookeeper_client_port
                  name: zookeeper-config
            - name: ZOOKEEPER_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  key: zookeeper_tick_time
                  name: zookeeper-config