apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
{{- with .Values.global.workloadScheduling.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.global.workloadScheduling.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
{{- end }}
      enableServiceLinks: false
      containers:
        - name: broker
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
            - containerPort: 29092
            - containerPort: 29093
          env:
            - name: KAFKA_NODE_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_node_id
            - name: KAFKA_PROCESS_ROLES
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_process_roles
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_controller_quorum_voters
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_listener_security_protocol_map
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_advertised_listeners
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_controller_listener_names
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_inter_broker_listener_name
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_offsets_topic_replication_factor
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_transaction_state_log_min_isr
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_transaction_state_log_replication_factor
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: kafka_group_initial_rebalance_delay_ms
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-config
                  key: cluster_id
          resources:
{{ toYaml .Values.resources | nindent 12 }}
