apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: {{ .Values.namespace }}
  labels:
    app: broker
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: kafka-internal
      port: 29092
      targetPort: 29092
      protocol: TCP
    - name: controller
      port: 29093
      targetPort: 29093
      protocol: TCP
  selector:
    app: broker
