apiVersion: v2
name: microservices
description: Umbrella chart for the microservices demo
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: metrics-server
    alias: metricsServer
    version: 0.1.0
    repository: "file://charts/metrics-server"
    condition: metricsServer.enabled
  - name: infrastructure
    version: 0.1.0
    repository: "file://charts/infrastructure"
  - name: applications
    version: 0.1.0
    repository: "file://charts/applications"
  - name: k8s-gateway
    version: 0.1.0
    repository: "file://charts/k8s-gateway"
    condition: k8sGateway.enabled
