global:
  namespace: microservices

infrastructure:
  namespace: microservices
  mysql:
    enabled: true
    fullnameOverride: mysql
    image: mysql:8.3.0
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    rootPassword: mysql
    persistence:
      enabled: true
      storageClassName: standard
      size: 1Gi
      hostPath: /data/mysql
    initSql: |
      CREATE DATABASE IF NOT EXISTS order_service;
      CREATE DATABASE IF NOT EXISTS inventory_service;

  mongodb:
    enabled: true
    fullnameOverride: mongodb
    image: mongo:7.0.5
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    rootUsername: root
    rootPassword: password
    database: product-service
    persistence:
      enabled: true
      storageClassName: standard
      size: 1Gi
      hostPath: /data/mongodb

  kafka:
    enabled: true
    broker:
      image: confluentinc/cp-kafka:7.5.0
      replicaCount: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 1Gi
      serviceName: broker
      brokerId: "1"
      zookeeperConnect: zookeeper:2181
      listenerSecurityProtocolMap: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      advertisedListeners: "PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092"
      offsetsTopicReplicationFactor: "1"
    zookeeper:
      image: confluentinc/cp-zookeeper:7.5.0
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      serviceName: zookeeper
      clientPort: "2181"
      tickTime: "2000"
    schemaRegistry:
      image: confluentinc/cp-schema-registry:7.5.0
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      serviceName: schema-registry
      hostName: schema-registry
      kafkaStoreBootstrapServers: broker:29092
      listeners: http://schema-registry:8081
    ui:
      image: provectuslabs/kafka-ui:latest
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      serviceName: kafka-ui
      clustersName: local
      clustersBootstrapServers: broker:29092
      dynamicConfigEnabled: "true"

  keycloak:
    enabled: true
    fullnameOverride: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    adminUser: admin
    adminPassword: admin
    hostname: keycloak.haint.fyi
    redirectUris:
      - https://frontend-next.haint.fyi
      - https://frontend-next.haint.fyi/*
      - https://frontend-next.haint.fyi/api/auth/callback/keycloak
    db:
      vendor: MYSQL
      host: keycloak-mysql
      database: keycloak
      user: keycloak
      password: password
    kcHttpEnabled: "true"
    kcHostnameStrict: "false"
    kcHostnameStrictHttps: "false"
    realmImport: ""

  keycloak-mysql:
    enabled: true
    fullnameOverride: keycloak-mysql
    image: mysql:8
    replicaCount: 1
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
    rootPassword: root
    database: keycloak
    user: keycloak
    password: password
    persistence:
      enabled: true
      storageClassName: standard
      size: 1Gi
      hostPath: /data/keycloak-mysql

  mailhog:
    enabled: true
    fullnameOverride: mailhog
    image: axllent/mailpit:v1.27
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  observability:
    enabled: true
    grafana:
      image: grafana/grafana:10.1.0
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      anonymousEnabled: "true"
      anonymousOrgRole: Admin
      disableLoginForm: "true"
      datasourceYml: |
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus.default.svc.cluster.local:9090
            editable: false
            jsonData:
              httpMethod: POST
              exemplarTraceIdDestinations:
                - name: trace_id
                  datasourceUid: tempo
          - name: Tempo
            type: tempo
            access: proxy
            orgId: 1
            url: http://tempo.default.svc.cluster.local:3100
            basicAuth: false
            isDefault: true
            version: 1
            editable: false
            apiVersion: 1
            uid: tempo
            jsonData:
              httpMethod: GET
              tracesToLogs:
                datasourceUid: 'loki'
              nodeGraph:
                enabled: true
          - name: Loki
            type: loki
            uid: loki
            access: proxy
            orgId: 1
            url: http://loki.default.svc.cluster.local:3100
            basicAuth: false
            isDefault: false
            version: 1
            editable: false
            apiVersion: 1
            jsonData:
              derivedFields:
                - datasourceUid: tempo
                  matcherRegex: "\\[.+,(.+?),"
                  name: TraceID
                  url: $${__value.raw}
    prometheus:
      image: prom/prometheus:v2.46.0
      replicaCount: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
      configYml: |
        global:
          scrape_interval: 2s
          evaluation_interval: 2s

        scrape_configs:
          - job_name: 'api-gateway'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: [ 'api-gateway.microservices.svc.cluster.local:9000' ]
          - job_name: 'product-service'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: [ 'product-service.microservices.svc.cluster.local:8080' ]
                labels:
                  application: 'Product Service'
          - job_name: 'order-service'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: [ 'order-service.microservices.svc.cluster.local:8081' ]
                labels:
                  application: 'Order Service'
          - job_name: 'inventory-service'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: [ 'inventory-service.microservices.svc.cluster.local:8082' ]
                labels:
                  application: 'Inventory Service'
          - job_name: 'notification-service'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: [ 'notification-service.microservices.svc.cluster.local:8083' ]
                labels:
                  application: 'Notification Service'
    loki:
      image: grafana/loki:main
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
    tempo:
      image: grafana/tempo:2.2.2
      replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      storage:
        size: 1Gi
        storageClassName: standard
        hostPath: /data/tempo
      configYml: |
        server:
          http_listen_port: 3100

        distributor:
          receivers:
            zipkin:

        storage:
          trace:
            backend: local
            local:
              path: /tmp/tempo/blocks

applications:
  namespace: microservices
  commonConfig:
    lokiUrl: http://loki.microservices.svc.cluster.local:3100/loki/api/v1/push
    managementZipkinTracingEndpoint: http://tempo.microservices.svc.cluster.local:9411
    productServiceUrl: http://product-service.microservices.svc.cluster.local:8080
    orderServiceUrl: http://order-service.microservices.svc.cluster.local:8081
    inventoryServiceUrl: http://inventory-service.microservices.svc.cluster.local:8082
    springKafkaBootstrapServers: broker.microservices.svc.cluster.local:29092
  apiGateway:
    enabled: true
    image: docker.io/hai2k2tt/api-gateway:0.0.1-SNAPSHOT
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 9000
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    config:
      issuerUri: https://keycloak.haint.fyi/realms/spring-microservices-security-realm
  productService:
    enabled: true
    image: docker.io/hai2k2tt/product-service:1.0-SNAPSHOT
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 8080
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    config:
      mongodbUri: mongodb://root:password@mongodb.microservices.svc.cluster.local:27017/product-service?authSource=admin
  orderService:
    enabled: true
    image: docker.io/hai2k2tt/order-service:1.0-SNAPSHOT
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 8081
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    config:
      datasourceUrl: jdbc:mysql://mysql.microservices.svc.cluster.local:3306/order_service
      schemaRegistryUrl: http://schema-registry.microservices.svc.cluster.local:8081
  inventoryService:
    enabled: true
    image: docker.io/hai2k2tt/inventory-service:1.0-SNAPSHOT
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 8082
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
    config:
      datasourceUrl: jdbc:mysql://mysql.microservices.svc.cluster.local:3306/inventory_service
  notificationService:
    enabled: true
    image: docker.io/hai2k2tt/notification-service:1.0-SNAPSHOT
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 8083
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    config:
      schemaRegistryUrl: http://schema-registry.microservices.svc.cluster.local:8081
  frontend:
    enabled: true
    image: docker.io/hai2k2tt/frontend:amd64
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 80
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
  frontendNext:
    enabled: true
    image: docker.io/hai2k2tt/frontend-next:amd64
    imagePullPolicy: Always
    replicaCount: 1
    service:
      port: 3001
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
    config:
      nextPublicApiBaseUrl: https://api.haint.fyi/api
      authUrl: https://frontend-next.haint.fyi
      authIssuer: https://keycloak.haint.fyi/realms/spring-microservices-security-realm
      authIssuerInternal: http://keycloak.microservices.svc.cluster.local:8080/realms/spring-microservices-security-realm
      authClientId: angular-client
      authClientSecret: ""
      authScope: openid profile offline_access
      authSecret: replace-with-a-long-random-string

k8sGateway:
  enabled: true
  namespace: microservices
  gateway:
    name: api-gateway
    className: nginx
    listeners:
      - name: http
        port: 80
        protocol: HTTP
  routes:
    - name: frontend-route
      hostname: frontend.haint.fyi
      backendRefName: frontend
      backendRefPort: 80
    - name: frontend-next-route
      hostname: frontend-next.haint.fyi
      backendRefName: frontend-next
      backendRefPort: 3001
    - name: api-route
      hostname: api.haint.fyi
      backendRefName: api-gateway
      backendRefPort: 9000
    - name: keycloak-route
      hostname: keycloak.haint.fyi
      backendRefName: keycloak
      backendRefPort: 8080
    - name: kafka-ui-route
      hostname: kafka-ui.haint.fyi
      backendRefName: kafka-ui
      backendRefPort: 8080
    - name: grafana-route
      hostname: grafana.haint.fyi
      backendRefName: grafana
      backendRefPort: 3000
    - name: tempo-route
      hostname: tempo.haint.fyi
      backendRefName: tempo
      backendRefPort: 3100
    - name: prometheus-route
      hostname: prometheus.haint.fyi
      backendRefName: prometheus
      backendRefPort: 9090
    - name: mailhog-route
      hostname: mailhog.haint.fyi
      backendRefName: mailhog
      backendRefPort: 8025
    - name: schema-registry-route
      hostname: schema-registry.haint.fyi
      backendRefName: schema-registry
      backendRefPort: 8081
    - name: loki-route
      hostname: loki.haint.fyi
      backendRefName: loki
      backendRefPort: 3100
