apiVersion: v2
name: observability
description: Grafana, Prometheus, Loki, Tempo
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: grafana
    version: 0.1.0
    repository: "file://charts/grafana"
  - name: prometheus
    version: 0.1.0
    repository: "file://charts/prometheus"
  - name: loki
    version: 0.1.0
    repository: "file://charts/loki"
  - name: tempo
    version: 0.1.0
    repository: "file://charts/tempo"
