apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy: { }
  template:
    metadata:
      labels:
        app: grafana
    spec:
      enableServiceLinks: false
      containers:
        - image: grafana/grafana:10.1.0
          name: grafana
          resources: { }
          ports:
            - containerPort: 3000
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: gf_auth_anonymous_enabled
                  name: grafana-config
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              valueFrom:
                configMapKeyRef:
                  key: gf_auth_anonymous_org_role
                  name: grafana-config
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              valueFrom:
                configMapKeyRef:
                  key: gf_auth_disable_login_form
                  name: grafana-config
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources/datasource.yml
              subPath: datasource.yml
              readOnly: true
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-config