apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  gf_auth_anonymous_enabled: "true"
  gf_auth_anonymous_org_role: "Admin"
  gf_auth_disable_login_form: "true"
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.default.svc.cluster.local:9090
        editable: false
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: tempo
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        url: http://tempo.default.svc.cluster.local:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
        apiVersion: 1
        uid: tempo
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: 'loki'
          nodeGraph:
            enabled: true
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        orgId: 1
        url: http://loki.default.svc.cluster.local:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: false
        apiVersion: 1
        jsonData:
          derivedFields:
            -   datasourceUid: tempo
                matcherRegex: \[.+,(.+?),
                name: TraceID
                url: $${__value.raw}