{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "system:%s" .Values.fullnameOverride | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "system:%s" .Values.fullnameOverride | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.fullnameOverride }}
    namespace: {{ .Release.Namespace }}
{{- end }}
