apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.microservices.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.microservices.svc.cluster.local:9411"
  API_GATEWAY_URL: "http://api-gateway.microservices.svc.cluster.local:9000"
  PRODUCT_SERVICE_URL: "http://product-service.microservices.svc.cluster.local:8080"
  ORDER_SERVICE_URL: "http://order-service.microservices.svc.cluster.local:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service.microservices.svc.cluster.local:8082"
  PAYMENT_SERVICE_URL: "http://payment-service.microservices.svc.cluster.local:8085"
  SHOP_SERVICE_URL: "http://shop-service.microservices.svc.cluster.local:8086"
  CUSTOMER_SERVICE_URL: "http://customer-service.microservices.svc.cluster.local:8087"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "broker.microservices.svc.cluster.local:29092"
