enabled: true
namespace: microservices
image: docker.io/hai2k2tt/landing-fe:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3005
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
config:
  adminFeUrl: https://admin-fe.haint.fyi
  shopFeUrl: https://shop-fe.haint.fyi
  customerFeUrl: https://customer-fe-next.haint.fyi
  customerWalletFeUrl: https://customer-wallet-fe.haint.fyi
  shopWalletFeUrl: https://shop-wallet-fe.haint.fyi
