enabled: true
namespace: microservices
image: docker.io/hai2k2tt/landing-fe:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3005
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
config:
  adminFeUrl: http://admin-fe.haint.fyi/admin
  shopFeUrl: http://shop-fe.haint.fyi/shop
  customerFeUrl: http://customer-fe-next.haint.fyi/customer
