enabled: true
namespace: microservices
image: hai2k2tt/frontend:latest
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 80
config:
  apiBaseUrl: http://api-gateway.microservices.svc.cluster.local:9000/api
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
