enabled: true
namespace: microservices
image: docker.io/hai2k2tt/shop-fe:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 3003
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
config:
  apiBaseUrl: http://api-gateway.microservices.svc.cluster.local:9000/api
  nextPublicApiBaseUrl: http://api.haint.fyi/api
  authUrl: http://shop-fe.haint.fyi
  authIssuer: http://keycloak.haint.fyi/realms/ecommerce-shop
  authIssuerInternal: http://keycloak.microservices.svc.cluster.local:8080/realms/ecommerce-shop
  authClientId: shop-fe-client
  authClientSecret: ""
  authScope: openid profile offline_access
  authCookiePrefix: shop-fe
  authCookieDomain: .haint.fyi
  authBasePath: /api/shop-fe/auth
  authSecret: replace-with-a-long-random-string
