enabled: true
namespace: microservices
image: docker.io/hai2k2tt/notification-service:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8083
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
config:
  schemaRegistryUrl: http://schema-registry.microservices.svc.cluster.local:8081
  mailHost: mailhog.microservices.svc.cluster.local
  mailPort: "1025"
