enabled: true
namespace: microservices
image: docker.io/hai2k2tt/notification-service:2-amd64
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8083
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
config:
  datasourceUrl: jdbc:postgresql://postgres.microservices.svc.cluster.local:5432/notification_service
  datasourceUsername: postgres
  datasourcePassword: postgres
  schemaRegistryUrl: http://schema-registry.microservices.svc.cluster.local:8081
  shopServiceUrl: http://shop-service.microservices.svc.cluster.local:8086
  shopNotificationTopic: shop-notifications
