apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: {{ .Values.namespace }}
data:
  LOKI_URL: {{ .Values.commonConfig.lokiUrl | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.commonConfig.managementZipkinTracingEndpoint | quote }}
  API_GATEWAY_URL: {{ .Values.commonConfig.apiGatewayUrl | quote }}
  PRODUCT_SERVICE_URL: {{ .Values.commonConfig.productServiceUrl | quote }}
  ORDER_SERVICE_URL: {{ .Values.commonConfig.orderServiceUrl | quote }}
  INVENTORY_SERVICE_URL: {{ .Values.commonConfig.inventoryServiceUrl | quote }}
  PAYMENT_SERVICE_URL: {{ .Values.commonConfig.paymentServiceUrl | quote }}
  SHOP_SERVICE_URL: {{ .Values.commonConfig.shopServiceUrl | quote }}
  CUSTOMER_SERVICE_URL: {{ .Values.commonConfig.customerServiceUrl | quote }}
  WALLET_SERVICE_URL: {{ .Values.commonConfig.walletServiceUrl | quote }}
  NOTIFICATION_SERVICE_URL: {{ .Values.commonConfig.notificationServiceUrl | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.commonConfig.springDataRedisHost | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.commonConfig.springDataRedisPort | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.commonConfig.springKafkaBootstrapServers | quote }}
