enabled: true
namespace: microservices
image: hai2k2tt/inventory-service:1.0-SNAPSHOT
imagePullPolicy: IfNotPresent
replicaCount: 1
service:
  port: 8082
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
config:
  datasourceUrl: jdbc:mysql://mysql.microservices.svc.cluster.local:3306/inventory_service
